name: CI Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pyp3]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip twine
          pip install flake8
          pip install mypy
      - name: Run Tests
        run: |
          python3 -m unittest discover tests
      - name: Run pep8 Linter
        run: |
          python3 -m flake8
      - name: Perform Type Check
        run: |
          mypy piuma/*.py
      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel
          python3 -m twine check dist/*